---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-travis
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20170919
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      excludes:
        /home/travis/build/woyager/db/.travis.yml
        /home/travis/build/woyager/db/molecule
        /home/travis/build/woyager/db/meta
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
